### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/nextcloud-dialogs#920]
Copy-Pasted notes from design review to be triaged and implemented:
* [x] Add button should look like in files app (#928)
* [x] Remove checkboxes for single select (https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/929)
* [x] If there are no files in a folder, show EmptyContent component (https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/930)
* [x] Hover on checkboxes should be a circle (Vue component issue) (https://github.com/nextcloud-libraries/nextcloud-vue/pull/4453)
* [x] Add icons to copy and move by default (#938 )
* [x] Move --> Move to [foldername] (#938 )
* [x] Change folder icon size to 20px (todo with F2V) (https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/962)
* [x] heading for the entire dialog should be center aligned with the dialog --> part of dialogs rework (https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/965)
  * [x] Have a heading or title prop, centered in the dialog 
* [x] Hover feedback for "home" should be circle --> Vue component, so forwarded in https://github.com/nextcloud-libraries/nextcloud-vue/issues/4519
* [x] checkboxes should not be shown above the header when you scroll (z-index of checkboxes too high) (https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/997)
* [x] Sorting --> last sorting from user in files app
  * [x] Have a default sorting by name for the time being (#949)

Descoped
* [ ] Exchange positions of text field and dropdown in "medium" screen size 
* [ ] Position of search box on the right? +  functionality of search --> to discuss
  * If the search does only filter it should be placed on the right of the bread crumbs, expandable like the talk search
  * If it really searches it can stay where it is

**Comment by susnux** [comment]
> Add icons to copy and move by default

Can someone recommend icons for this purpose?
I am not happy with the ones I found on MDI :sweat_smile:  @szaimen @nimishavijay

**Comment by skjnldsv** [comment]
> Can someone recommend icons for this purpose?

Move is [`folder-move`](https://pictogrammers.com/library/mdi/icon/folder-move/)
Copy is [`content-copy`] (https://pictogrammers.com/library/mdi/icon/content-copy/)

**Comment by skjnldsv** [comment]
> But they're not available in our `@mdi/svg` or `vue-material-design-icons` libs it seems 🤔

Ah, they are, but renamed `file-multiple.svg` and `folder-multiple.svg`
| File | Folder |
|:---------:|:------:|
|![file-multiple](https://github.com/nextcloud-libraries/nextcloud-dialogs/assets/14975046/112019ee-d8c9-44cd-9a09-0b4b71d5f28a)|![folder-multiple](https://github.com/nextcloud-libraries/nextcloud-dialogs/assets/14975046/0744fec0-34ef-4ca9-b301-37eef58e043c)|
